spring:
  #springboot 2.0默认使用的连接池是Hikari来代替druid,以下配置Hikari也可以使用，同时可配置额外hikari特有配置
  datasource:
    url: jdbc:mysql://localhost:3306/sys_db_demo?serverTimezone=UTC
    # mysql6.0以后要使用com.mysql.cj.jdbc.Driver驱动，而非com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
#  mvc:
#    static-path-pattern: /static/**
#  resources:
#    static-locations: ["/static","/templates"]
mybatis:
  mapper-locations: classpath:com/surfilter/ssm/dbconfig/*.xml
  type-aliases-package: com.surfilter.bootmybatis.ssm.model

