spring:
  #springboot 2.0 默认连接池就是Hikari，而非druid,但是以下方式配置Hikari仍然可以识别
  datasource:
    url: jdbc:mysql://localhost:3306/sys_db_demo?serverTimezone=UTC
    # mysql6.0以后使用com.mysql.cj.jdbc.Driver驱动，而非com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:com/surfilter/ssm/dbconfig/*.xml
  type-aliases-package: com.surfilter.bootmybatis.ssm.model
